name: Production deploy to VPS

on:
  push:
    branches:
      - master-java
      - prod-workflow
jobs:
  deploy:
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # или любая другая версия Java, необходимая для вашего приложения
          distribution: 'oracle'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --exclude-task test

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/distributions/*.zip
          overwrite: true

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_WORKING_DIRECTORY }}
            rm -f *.jar # Удаление всех JAR-файлов из директории
            artifact_url=$(curl -L -s -o /dev/null -w "%{url_effective}" -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}/zip")
            wget $artifact_url -O app.zip
            systemctl stop cocker.service
            unzip app.zip
            unzip java-discord-bot-1.0.zip
            systemctl start cocker.service
