name: Production deploy to VPS

on:
  push:
    branches:
      - master-java
      - prod-workflow
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: |
        scp -r ${{ github.workspace }} root@147.45.77.142:/opt/captain-cocker
