name: Production deploy to VPS

on:
  push:
    branches:
      - master-java

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        scp -r / username@your_vps_ip:/path/to/destination
        ssh username@your_vps_ip "cd /path/to/destination && ./restart_script.sh"
